import Foundation

/// Locates ShotnixCore's SwiftPM resource bundle WITHOUT ever touching the
/// generated `Bundle.module` accessor.
///
/// That accessor, as generated by `swift build` for executable products,
/// searches exactly two places: the .app ROOT (where a signed bundle cannot
/// legally contain files) and the build machine's absolute `.build` path.
/// In a released app it therefore fatalErrors on every machine except the one
/// that built it — GitHub issue #25, which crashed every public DMG at launch.
///
/// This finder checks where `build-app.sh` actually installs the bundle
/// (Contents/Resources) plus the dev layouts, and degrades to nil instead of
/// crashing; callers must treat a missing bundle as "resource unavailable".
///
/// NEVER reference `Bundle.module` anywhere in ShotnixCore.
enum ShotnixResources {

    static let bundle: Bundle? = locate()

    static func url(forResource name: String, withExtension ext: String) -> URL? {
        bundle?.url(forResource: name, withExtension: ext)
    }

    private static func locate() -> Bundle? {
        let name = "Shotnix_ShotnixCore.bundle"
        let candidates: [URL?] = [
            Bundle.main.resourceURL,                                // .app: Contents/Resources (build-app.sh)
            Bundle.main.bundleURL,                                  // CLI-style flat layout
            Bundle.main.executableURL?.deletingLastPathComponent(), // swift build dev layout (.build/…/release)
        ]
        for candidate in candidates {
            if let url = candidate?.appendingPathComponent(name),
               let bundle = Bundle(url: url) {
                return bundle
            }
        }
        return nil
    }
}
